# Generated by Django 3.2.7 on 2021-09-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='item_url',
            field=models.URLField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'slug')},
        ),
    ]
