# Generated by Django 3.2.7 on 2021-09-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_meet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='item_url',
            field=models.URLField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='meet',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
