# Generated by Django 3.2.7 on 2021-09-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210918_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='item_url',
        ),
    ]
