# Generated by Django 3.2.7 on 2021-09-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_meet_item_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='slug',
        ),
    ]
