# Generated by Django 3.2.7 on 2021-09-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_category_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
