# Generated by Django 3.2.7 on 2021-09-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_meet_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='amount',
        ),
    ]
