# Generated by Django 3.2.7 on 2021-09-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_image_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='images',
        ),
    ]
